config/routes.rb
OgDatabase::Application.routes.draw do
  get 'definitions/show'

  resources :demographics, :shallow=>true do
    collection do
      get 'search'
      post 'search'
      get 'recurrences'
      get 'reports'
      post 'reports'
    end
    resources :follow_ups
    resources :pathologies
    resources :treatments
    resources :staging_cts
    resources :stagings
    resources :exposures
    resources :samples
    resources :ffpes
  end

  get 'logout', to: 'demographics#logout'
  root :to => 'demographics#search'
end

app/models/asa_grade.rb
class AsaGrade < ApplicationRecord
end

app/models/drug.rb
class Drug < ApplicationRecord
  has_many :medications
end

app/models/exposure.rb
class Exposure < ApplicationRecord
  belongs_to :demographic
  validates :demographic, :presence => true


#  has_many :barrett_managements_lookups, :through => :previous_barrett_managments
  has_many :presenting_complaints
  has_many :presenting_complaint_lookups, :through => :presenting_complaints

  #FIXME has_many without plural, is this correct?
  has_many :family_history_of_og_cancer
  accepts_nested_attributes_for :family_history_of_og_cancer

  has_many :family_history_of_other_cancer
  accepts_nested_attributes_for :family_history_of_other_cancer

  has_many :co_morbidities
  has_many :co_morbidity_lookups, :through => :co_morbidities

  has_many :medications
  has_many :drugs, :through => :medications
  accepts_nested_attributes_for :medications

  audited

  def bmi
      (100*weight/height**2).floor.to_f / 100 unless weight.nil? || height.nil?
  end
end

app/models/ffpe.rb
class Ffpe < ApplicationRecord
  belongs_to :demographic
end

app/models/follow_up.rb
class FollowUp < ApplicationRecord
  belongs_to :demographic

  has_many :evidence_for_recurrences
  has_many :evidence_for_recurrence_lookups, :through => :evidence_for_recurrences

  audited

  validates_with Validators::FollowUpValidator

  def overall_survival_months
    0
  end
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/grading.rb
class Grading < ApplicationRecord
end

app/models/histology.rb
class Histology < ApplicationRecord
end

app/models/medication.rb
class Medication < ApplicationRecord
  belongs_to :exposure
  belongs_to :drug
  belongs_to :length_of_use

  validates :exposure, :drug, presence: true
end

app/models/pathology.rb
class Pathology < ApplicationRecord
  belongs_to :demographic

  has_many :barretts_adjacent_to_tumours
  has_many :barretts_adjacent_lookups, :through => :barretts_adjacent_to_tumours

  after_initialize :set_defaults

  audited

  def set_defaults
    self.resection_pathology_number ||= "UB" if self.respond_to?(:resection_pathology_number)
  end

end

app/models/response.rb
class Response < ApplicationRecord
end

app/models/sample.rb
class Sample < ApplicationRecord
  belongs_to :demographic

  def extra
    if self[:extra].nil? || self[:extra] == ""
      Hash.new
    else
      YAML.load(self[:extra])
    end
  end

  def extra=(v)
      self[:extra] = v.to_yaml
  end

  def storage_location
    if has_storage_location?
      extra[:storage_location].gsub('In Transit Container', '').strip
    end
  end

  def interval
    if self.collection_time && self.frozen_time
      (self.frozen_time - self.collection_time).to_i / 60
    else
      nil
    end
  end

  def self.ca_fields
    %w(label barcode sample_class sample_type collection_time frozen_time storage_location)
  end

  def has_storage_location?
    extra.present? && extra.key?(:storage_location) && extra[:storage_location].is_a?(String)
  end
end

app/models/smoker.rb
class Smoker < ApplicationRecord
end

app/models/specimen.rb
class Specimen
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  def persisted?
    false
  end

  def self.find_by_participant_id(participant_id)

  end

  def demographic
    #FIXME get demograph from data
    Demographic.all.first
  end

  def label
    @label
  end

  def barcode
    @barcode
  end

  def comment
    @comment
  end
  
  def collected_at
    @collected_at
  end

  def received_at
    @received_at
  end

  private
  def self.create_from_local_db(participant_id)
    Sample
  end

  def self.create_from_remote_db(participant_id)
    @label = data[:label]
    @barcode = data[:barcode]
    if data.has_key? :specimen_events
      data[:specimen_events].each do |event|
        if event[:object] == "CollectionEventParameters"
          @collected_at = event[:data][:time]
        end
        if event[:object] == "ReceivedEventParameters"
          @received_at = event[:data][:time]
        end
      end
    end

  end

  def initialize(data)
  end

end

app/models/staging.rb
class Staging < ApplicationRecord
  belongs_to :demographic

  has_one :staging_ct
  accepts_nested_attributes_for :staging_ct

  has_one :staging_ctpet
  accepts_nested_attributes_for :staging_ctpet

  has_one :staging_endoscopic_ultrasound
  accepts_nested_attributes_for :staging_endoscopic_ultrasound

  has_one :post_chemotherapy_restaging
  accepts_nested_attributes_for :post_chemotherapy_restaging

  has_one :laparoscopy
  accepts_nested_attributes_for :laparoscopy

  has_one :other_investigation
  accepts_nested_attributes_for :other_investigation

  has_one :final_mdt_stage
  accepts_nested_attributes_for :final_mdt_stage

  audited

  def method_missing(method_name, *arguments, &block)
    if method_test(method_name.to_s)
      Staging.has_one_tables.each do |name|
        if method_name.to_s.starts_with?(name)
          local_method = method_name.to_s.sub("#{name}_", '')
          if self.public_send(name).nil?
            return ''
          else
            return self.public_send(name).public_send(local_method)
          end
        end
      end
      super
    end
  end

  def respond_to_missing?(method_name, include_private = false)
    super || method_test(method_name.to_s)
  end

  private
  def method_test(method_name)
    Staging.has_one_tables.each do |name|
      if method_name.starts_with?(name)
        local_method = method_name.sub("#{name}_",'')
        const = name.camelize.constantize
        return const.new.respond_to? local_method
      end
    end
    false
  end

  def self.has_one_tables
    selector = -> (assoc) { assoc.is_a? ActiveRecord::Reflection::HasOneReflection}
    Staging.reflect_on_all_associations
      .select(&selector)
      .collect(&:name)
      .collect(&:to_s)
      .sort { |a,b| b.length <=> a.length }
  end
end

app/models/tnm_m.rb
class TnmM < ApplicationRecord
end

app/models/tnm_n.rb
class TnmN < ApplicationRecord
end

app/models/tnm_t.rb
class TnmT < ApplicationRecord
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :demographic

  audited
end

app/models/user.rb
class User < ApplicationRecord

end

app/views/layouts/_demographic_navigation.html.erb
  <li><%= link_to_demographic %></li>
  <li><%= link_to_new_or_edit :exposure %></li>
  <li><%= link_to_new_or_edit :staging %></li>
  <li><%= link_to_new_or_edit :treatment %></li>
  <li><%= link_to_new_or_edit :pathology %></li>
  <li><%= link_to_new_or_edit :follow_up %></li>
  <li><%= link_to_new_or_edit :ffpe %></li>
  <li><%= link_to_samples %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? content_for(:title) : "OG Database" %></title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>
        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body data-log-level="<%= js_loglevel %>">
    <div class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Oesophageal DB', root_path, class: 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li id="navbar-list" class="active">
              <%= link_to "Scoped Search", root_path %>
            </li>
            <li id="navbar-new">
              <%= link_to "New Demographic", new_demographic_path %>
            </li>
            <li id="navbar-excel">
              <%= link_to "DB To Excel", (reports_demographics_path + '.xlsx') %>
            </li>
          </ul>
          <div class="navbar-right">
          <%= form_for :search, url: search_demographics_path, html: { class: 'navbar-form navbar-left' } do %>
            <div class="form-group">
              <input type="text" class="form-control input-group" placeholder="Search" id="q" name="q">
            </div>
            <button type="submit" class="btn btn-primary">Go</button>
            <% end %>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                   role="button" aria-expanded="false">
                  <i class="fa fa-user"></i>
                  <%= current_user.name %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Details", "#" %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Sign Out", "#" %></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <% if content_for? :navbar_secondary %>
    <div class="navbar navbar-default navbar-secondary">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <%= yield :navbar_secondary %>
        </ul>
      </div>
    </div>
    <% end %>
    <div id="main" class="container-fluid">
      <div class="row">
        <div class="col-lg-8 pull-right">
          <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: name %>
          <% end -%>
        </div>
      </div>
      <%= yield %>
    </div>
    <footer>
      <%= render partial: 'footer' %>
    </footer>
  </body>
</html>

app/views/layouts/sample_table.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OgDatabase</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
   <div class="navbar span-24 last">
    <div class="navbar_inner span-24">
	<ul class="horizontal_menu span-24">
          <li><%= link_to "New Demographic", new_demographic_path %></li>
          <%= render 'layouts/demographic_navigation' if get_demographic.persisted? %>
	  <li><%= link_to "Search", search_demographics_path %></li>
          <li><%= link_to "Exit Path", logout_path %></li>
	</ul>
	<ul>
	  <li><b><%= session[:cas_user] %></b></li>
        </ul>
    </div>
   </div>
  <div class="clear span-24 last container">
    <div class="content span-24">
      <div class="content_inner span-24">
	<%= yield %>
      </div>
    </div>
   </div>
</body>
</html>